### ISSUE TITLE
ERROR: Cannot open config file: /inspircd/conf/inspircd.conf

### ISSUE THREAD

**Issue by DracoMilesX** [Adam-/inspircd-docker#12]
Error when creating container.

The Dockerfile doesn't copy the conf directory to the right place. U guys have copy conf to /conf instead of /inspircd/conf.

Perhaps because u set the workdir after the copy?

**Comment by SISheogorath** [comment]
Can you provide the command you used to start? 

Would be helpful because we actually create a symlink in  the [Dockerfile](https://github.com/Adam-/inspircd-docker/blob/master/Dockerfile#L32)

But we should may start inspircd with a parameter to just use /conf directly.

**Comment by DracoMilesX** [comment]
> docker run --name inspircd \
> --memory=128M --memory-swap=256M \
> -p 6667:6667 -p 6697:6697 -p 7000:7000 -p 7001:7001 \
> -v /volume4/Drive4/Apps/inspircd:/inspircd/conf/ \
> inspircd/inspircd-docker

**Comment by SISheogorath** [comment]
Ah!

The point is inspircd needs a config file to start. it doesn't create one. This leads you to the problem that you need to write a config file before you start. We should may simply copy the config into the volume as long as no one exists. Good Point I'll fix that

You can run inspircd right now without volume or copy the content of our "conf" directory into your directory which you've mounted

**Comment by DracoMilesX** [comment]
Thanks for the tip I forgot about that docker doesn't copy content to volumes only newly created ones<.<
