### ISSUE TITLE
Specify only partial config

### ISSUE THREAD

**Issue by aland** [Adam-/inspircd-docker#45]
Is it possible to use the default inspircd.conf file but then also load a custom config which specifes only a few settings (e.g. opers, permanent channels..) without the inspircd.conf file being present when the container first starts?

I've tried with an arbitrary file in the /conf directory but it isn't loaded. I've also tried with an existing file (opers.conf) but it is overwritten on first run.

Example: `/ircd/conf/site.conf` contains:
`<permchannels channel="#help" modes="nt" topic="Help.">`

Then run:
`docker run -d -p 6667:6667 -v /ircd/conf/:/inspircd/conf/ inspircd/inspircd-docker`

**Comment by SISheogorath** [comment]
Currently it's not possible, but I'm working on an implementation.

Right now you can only get a copy of the config by provide the directory and then modify it as you need.

Pull requests are welcome :)

**Comment by aland** [comment]
Great, thanks for letting me know. I can stop pulling my hair out thinking it should work.

Only idea I had now was to check for another environment variable which holds the name of additional config to load and check this in the config.sh - but I don't think it would work since config.sh runs before all the modules are loaded.

**Comment by SISheogorath** [comment]
In general it's not a problem. The config for modules is loaded during the module initialization or later. And this is way after the whole config is read and parsed by InspIRCd.

So feel free to modify the `config.sh`. But in general as already mentioned: Simply load the mount the modified config is the easiest way.

If you want to run it in Swarm-mode or something, you can also build in your own config.

**Comment by aland** [comment]
I appreciate your time, just wanted to mention that it seems to be  necessary to include the customised inspircd.conf file before the container is ran for the first time. What I was doing was `run`ning the image so that it would populate the volume, then modifying the files in the volume and restarting the container. 
This would produce cryptic error messages like `Syntax error - start of tag expected at /inspircd/conf/inspircd.conf:542:1 (last tag was on line 534)` which made me think I had some problem with my changes.

So I'm now storing inspircd.conf, modules.conf et al modifed as required and using`COPY conf/*.conf /conf/` in my Dockerfile so that the config files are pre-populated.

**Comment by SISheogorath** [comment]
This is in general not a problem of the docker image. It's a InspIRCd "bug". Locateded here: https://github.com/inspircd/inspircd/blob/insp20/src/configparser.cpp#L268-L269

It's part of the config parser and as work around you can simply delete the last comment section or add a line break a the end (iirc this solves the problem). Maybe @Adam- can tell us more details. 

In general the image is build to simply allow you to add your configs by extending it.
You can use a Dockerfile like this one:

```
FROM inspircd:latest
COPY conf/ /inspircd/conf/
```

Simply place this Dockerfile into a directory and your configs into a sub directory called `conf`. That's it :)

**Comment by SISheogorath** [comment]
A fix is incoming: #48 

I currently think about what's the perfect solution. Because right now loading modules possibly fails because `m_md5` and other "required" modules are loaded afterwards.

Feel free to test it :)

**Comment by aland** [comment]
Works for me!
