### ISSUE TITLE
Oper login issue

### ISSUE THREAD

**Issue by DracoMilesX** [Adam-/inspircd-docker#49]
I tried to configure the oper for my inspircd server except it keeps on stating that the fields login, password and hosts did not match. This happens when using the default opers.conf.example (renamed to opers.conf and moved to /conf) as well including the load of the module in my inspircd.conf and with the docker run comment with the variables:

Docker run command:

> docker run -d \
> --name inspircd \
> --memory=128M \
> --memory-swap=256M \
> -p 6697:6697 \
> -p 7001:7001 \
> -e INSP_OPER_NAME=test\
> -e INSP_OPER_PASSWORD=test \
> -e INSP_OPER_HOST=*@* \
> -e INSP_OPER_HASH=hmac-sha256 \
> -e INSP_OPER_SSONLY=yes \
> -v /volume4/Drive4/Apps/inspircd:/inspircd/conf/ \
> inspircd/inspircd-docker

Noticed I used old conf files as well so did remove everything and let inspircd create everything automatic again and same issue exist but this time it only says that the password doesn't match

**Comment by SISheogorath** [comment]
Oh it is possible a misunderstanding.

You have to provide the hashed password. Not the clear text one. 

To create one, connect to the InspIRCd and use `/mkpasswd hmac-sha256 yourpassword`.

**Comment by SISheogorath** [comment]
After a check back I noticed that the documentation is not clear about it. Well extend it :)

**Comment by DracoMilesX** [comment]
Ah ok thanks for the information got it to work now with '<hash>'.

Might as well be a suggestion that it automatic converts to hashed password? Dunno if it's even possible or requires to much work.

Still odd that it didn't accept the password for plain text and hashed from the opers.conf the first time. But w/e. The variables work

**Comment by SISheogorath** [comment]
This container only contains InspIRCd. But @adam- and me also work on an anope container. 

We build the whole setup following most of the best practices of Docker official images and provide one process per container. Current ETA for a basically usable Anope container is 2 weeks.

**Comment by SISheogorath** [comment]
@DracoMilesX can you check the possible fix for this issue:

https://github.com/Adam-/inspircd-docker/blob/fix/issue-49/README.md

Would you say it's easier to find out, what you have to enter there?

**Comment by DracoMilesX** [comment]
@SISheogorath Yeah that looks better. Personally I would change the description to:
> Hashed oper password

The wording kinda feels odd with the "for usage with /oper"

and modify the "/oper <username> <password>" to "/oper <username> <plaintextpassword>"

But this might just be me going full retard.

**Comment by SISheogorath** [comment]
Thanks for the feedback :) I think the example is a better solution than providing longer example values to replace :)
